### ISSUE TITLE
Use another file name system

### ISSUE THREAD

**Issue by tianheg** [andybyers21/notes.ajb.app#7]
The timestamp isn't good for me, and your notes name way seems didn't serve as a visual aid for us human. So I think we should use another file name system: `x.x.md`.

Examples: 1.0.md: 1.1.md, 1.2.md, 1.3.md... 2.0.md: 2.1.md, 2.2.md, 2.3.md...

Naming is not limited to numbers, but can also be combined with letters.

The idea is from [A digital approach to Luhmann’s Zettelkasten (Slip Box)](https://tevinzhang.com/digital-zettelkasten/), hope it will help you.

**Comment by andybyers21** [comment]
I originally tried an approach like this (1_2b1c.md etc) however this quickly became cumbersome and unnecessarily complicated as my system is designed to create symlinks automatically based on the content of the note, similar to [Andy Matuschak's system](https://notes.andymatuschak.org). As we are using a visual interface with index's an additional layer of index became unnecessary.
